"""Private graph materialisation and block-coordinate fitting."""

from __future__ import annotations

import logging
import math
from dataclasses import replace

import torch

from entlearn._warnings import _warn
from entlearn.network.blocks.classification import _ClassificationBlock
from entlearn.network.blocks.hidden import _HiddenBlock
from entlearn.network.blocks.input import _StandardInputBlock
from entlearn.network.blocks.input_common import refresh_log_partition_, update_affiliations_
from entlearn.network.blocks.manifold import _ManifoldInputBlock
from entlearn.network.blocks.regression import _RegressionBlock
from entlearn.network.blocks.types import (
    _InputBlock,
    _RuntimeBlock,
)
from entlearn.network.build import _BuiltRecipe
from entlearn.network.data import _StagedData
from entlearn.network.initialisation.connections import initialise_hidden_chain_
from entlearn.network.session import _CompiledGraph, _FitSession
from entlearn.network.state import (
    InitialState,
    _ClassificationParameters,
    _FittedNetwork,
    _RegressionParameters,
    _Trajectory,
)
from entlearn.primitives.normalise import _eps
from entlearn.recipe import ClassificationHead, Hidden, Input, RegressionHead

# Multiple of the dtype machine precision that a loss rise must exceed before it counts as
# a real increase rather than round-off accumulated in the reduction.
_LOSS_NOISE_EPS_MULTIPLE = 256


class LossIncreaseWarning(UserWarning):
    """The monitored loss increased beyond its numerical noise threshold."""


class ConvergenceWarning(UserWarning):
    """One or more fit candidates exhausted their iterations without converging."""


def loss_noise_threshold(previous: float, dtype: torch.dtype) -> float:
    """Return the largest rise from ``previous`` that still counts as round-off."""
    return _LOSS_NOISE_EPS_MULTIPLE * _eps(dtype) * max(1.0, abs(previous))


def _materialise(
    built: _BuiltRecipe, data: _StagedData, initial_state: InitialState
) -> _FitSession:
    """Create the private fitted graph, open its fit session and assign the initial affiliations.

    Unless the input geometry was captured from a fitted model, the categorical centroids
    then take their exact update from those affiliations.

    ``initial_state`` must be ``resolve_state``'s output, or geometry generated by
    ``Network.initialise`` for the same staged ``data``: its tensors are adopted
    without further validation.

    Raises:
        ValueError: If ``initial_state`` does not describe this Recipe's connections.
    """
    input_block: _InputBlock
    if isinstance(built.input, Input):
        input_block = _StandardInputBlock.make_block(built.input, initial_state, data)
    else:
        input_block = _ManifoldInputBlock.make_block(built.input, initial_state, data)
    blocks: dict[str, _RuntimeBlock] = {input_block.description.name: input_block}
    K_source = input_block.K
    parameters = {group.description.name: group for group in initial_state.parameters}
    for description in built.topological_blocks[1:-1]:
        assert isinstance(description, Hidden)
        (connection,) = built.incoming[description.name]
        hidden = _HiddenBlock.make_block(description, data, connection, K_source)
        blocks[description.name] = hidden
        K_source = hidden.K
    supplied = parameters.get(built.head.name)
    if isinstance(built.head, ClassificationHead):
        assert supplied is None or isinstance(supplied, _ClassificationParameters)
        head = _ClassificationBlock.make_block(built.head, data, K_source, supplied)
    elif isinstance(built.head, RegressionHead):
        assert supplied is None or isinstance(supplied, _RegressionParameters)
        head = _RegressionBlock.make_block(built.head, data, K_source, supplied)
    else:
        raise TypeError("unsupported Recipe head description")
    blocks[head.description.name] = head
    expected_connections = tuple(connection.name for connection in built.connections)
    actual_connections = tuple(name for name, _ in initial_state.connection_sub_seeds)
    if actual_connections != expected_connections:
        raise ValueError("InitialState connection names do not match the Recipe")
    graph = _CompiledGraph(
        recipe=built.recipe,
        order=tuple(description.name for description in built.topological_blocks),
        connections=tuple(
            connection
            for description in built.topological_blocks
            for connection in built.outgoing[description.name]
        ),
        incoming=built.incoming,
        outgoing=built.outgoing,
        blocks=blocks,
        connection_sub_seeds=initial_state.connection_sub_seeds,
        training_rows=data.X_cont.shape[0],
    )
    session = _FitSession.open(graph, data)
    update_affiliations_(input_block, session)
    geometry = initial_state.input_geometry
    generated = geometry is not None and not geometry.captured
    if isinstance(input_block, _StandardInputBlock) and generated:
        input_block.start_categorical_centroids_(session)
    initialise_hidden_chain_(session, initial_state.parameters)
    return session


def _fit_iteration_(session: _FitSession) -> None:
    """Run one complete head-to-input block-coordinate iteration."""
    graph = session.graph
    graph.head.update_parameters_(session)
    for name in reversed(graph.order[1:-1]):
        block = graph.blocks[name]
        assert isinstance(block, _HiddenBlock)
        block.update_parameters_(session)

    graph.input.update_parameters_(session)


def _loss(session: _FitSession) -> float:
    """Return block then connection losses in stable forward graph order."""
    workspace = session.workspace
    workspace.loss.zero_()
    graph = session.graph
    for name in graph.order:
        block = graph.blocks[name]
        block.partial_loss_(session)
    for connection in graph.connections:
        target = graph.blocks[connection.target]
        if isinstance(target, _HiddenBlock):
            target.incoming[connection.name].partial_loss_(
                target.gamma,
                graph.affiliations(connection.source),
                session,
            )
    return float(workspace.loss.item())


def _converged(history: list[float], tol: float, dtype: torch.dtype) -> bool:
    """Return whether the final relative loss change meets ``tol``."""
    if len(history) < 2:
        return False
    previous, current = history[-2:]
    return abs(current - previous) / max(abs(previous), _eps(dtype)) <= tol


def _record_loss_warning(session: _FitSession, history: list[float], offset: int = 0) -> None:
    """Record and emit a loss increase beyond the numerical noise threshold.

    ``offset`` is the count of iterations completed before this operation, so that a
    continued trajectory names the same iteration as its logs and its loss history.
    """
    if len(history) < 2:
        return
    previous, current = history[-2:]
    difference = current - previous
    threshold = loss_noise_threshold(previous, session.data.X_cont.dtype)
    if difference <= threshold:
        return
    message = (
        f"loss increased at iteration {offset + len(history) - 1} by {difference:.6g} "
        f"(noise threshold: {threshold:.6g})"
    )
    session.warning_messages.append(message)
    _warn(message, LossIncreaseWarning)


def _record_checkpoint_warning(
    session: _FitSession,
    stored: float,
    recomputed: float,
    previous_dtype: torch.dtype,
) -> None:
    """Warn about a changed checkpoint without rejecting compatible continuation."""
    scale = max(abs(stored), abs(recomputed))
    threshold = max(
        loss_noise_threshold(scale, previous_dtype),
        loss_noise_threshold(scale, session.data.X_cont.dtype),
    )
    if (
        math.isfinite(stored)
        and math.isfinite(recomputed)
        and abs(recomputed - stored) <= threshold
    ):
        return
    message = (
        f"resume checkpoint loss differs: stored={stored:.17g}, "
        f"recomputed={recomputed:.17g}, threshold={threshold:.6g}; "
        "data, weights or numerical execution may differ. "
        "The retained convergence history is unchanged."
    )
    session.warning_messages.append(message)
    _warn(message, UserWarning)


def _fit(
    built: _BuiltRecipe,
    data: _StagedData,
    initial_state: InitialState,
    *,
    max_iter: int,
    tol: float,
    logger: logging.Logger | None = None,
    verbose: int = 0,
) -> tuple[_CompiledGraph, _Trajectory]:
    """Fit one candidate and return its compiled graph and trajectory."""
    session = _materialise(built, data, initial_state)
    for description in built.topological_blocks:
        if isinstance(description, Hidden) and description.K == 1:
            message = (
                f"hidden block {description.name!r} has K = 1: a single cluster carries no "
                "information and the head degrades to the target marginal"
            )
            session.warning_messages.append(message)
            _warn(message, UserWarning)
    trajectory = _optimise(session, max_iter=max_iter, tol=tol, logger=logger, verbose=verbose)
    return session.graph, trajectory


def _optimise(
    session: _FitSession,
    *,
    max_iter: int,
    tol: float,
    logger: logging.Logger | None,
    verbose: int,
    previous: _FittedNetwork | None = None,
) -> _Trajectory:
    """Run complete iterations, optionally extending an existing trajectory.

    The retained checkpoint tests convergence before any new coordinate update.
    The new operation's initial loss is used for convergence and warning comparisons
    after its first step, but is never appended as a second checkpoint.
    """
    history = [_loss(session)]
    offset = 0 if previous is None else previous.trajectory.n_iter
    _report_loss(logger, verbose, offset, history[0])
    converged = False
    if previous is not None:
        prior = previous.trajectory
        _record_checkpoint_warning(
            session,
            prior.loss_history[-1],
            history[0],
            previous.schema.computation_dtype,
        )
        # Changing numerical precision alone must not reopen an accepted stop.
        converged = (prior.converged and tol >= previous.tol) or _converged(
            list(prior.loss_history), tol, session.data.X_cont.dtype
        )
    n_iter = 0
    remaining = max(0, max_iter - offset)
    for iteration in range(1, remaining + 1):
        if converged:
            break
        _fit_iteration_(session)
        history.append(_loss(session))
        _record_loss_warning(session, history, offset)
        _report_loss(logger, verbose, offset + iteration, history[-1])
        n_iter = iteration
        converged = _converged(history, tol, session.data.X_cont.dtype)
    trajectory = _Trajectory(
        loss_history=tuple(history),
        n_iter=n_iter,
        converged=converged,
        warnings=tuple(session.warning_messages),
    )
    if previous is not None:
        prior = previous.trajectory
        trajectory = replace(
            trajectory,
            loss_history=prior.loss_history + trajectory.loss_history[1:],
            n_iter=offset + n_iter,
            warnings=prior.warnings + trajectory.warnings,
        )
    refresh_log_partition_(session.graph.input, session)
    _report_summary(logger, verbose, trajectory)
    return trajectory


def _report_loss(logger: logging.Logger | None, verbose: int, iteration: int, loss: float) -> None:
    """Report a live or retained iteration through the Network's logging policy."""
    if logger is not None and verbose >= 2:
        if iteration == 0:
            logger.debug("initial loss = %.6g", loss)
        else:
            logger.debug("iter %d: loss = %.6g", iteration, loss)


def _report_summary(logger: logging.Logger | None, verbose: int, trajectory: _Trajectory) -> None:
    """Report a completed candidate through the Network's logging policy."""
    if logger is not None and verbose >= 1:
        logger.info(
            "fit finished: %s after %d iterations; loss = %.6g",
            "converged" if trajectory.converged else "reached max_iter",
            trajectory.n_iter,
            trajectory.loss_history[-1],
        )
